#!/usr/bin/bash
"""
Setup Sound Effects Library for Enhanced Audiobook
Downloads free CC-licensed sounds from Freesound.org

Usage: ./scripts/setup-audiobook-sounds.sh
"""

SOUNDS_DIR="$HOME/.jarvis/sounds"

echo "🔊 Setting up audiobook sound effects library"
echo "=============================================="

# Create directory structure
mkdir -p "$SOUNDS_DIR"/{weather,nature,actions,ambient}

echo "✅ Created directory structure"
echo ""
echo "📥 Sound effects library setup:"
echo ""
echo "MANUAL DOWNLOAD REQUIRED (Free sources):"
echo ""
echo "1. Freesound.org (CC licenses)"
echo "   https://freesound.org/"
echo "   - Search: 'rain', 'thunder', 'wind', etc"
echo "   - Download .ogg or .wav files"
echo "   - Place in ~/.jarvis/sounds/weather/"
echo ""
echo "2. BBC Sound Effects (Free for personal use)"
echo "   https://sound-effects.bbcrewind.co.uk/"
echo "   - 16,000+ sound effects"
echo "   - Download .wav, convert to .ogg with: ffmpeg -i sound.wav sound.ogg"
echo ""
echo "3. OpenGameArt.org"
echo "   https://opengameart.org/art-search-advanced?keys=&field_art_type_tid%5B%5D=13"
echo "   - CC0/CC-BY licensed"
echo "   - Search for ambient sounds"
echo ""
echo "4. Zapsplat (Free with attribution)"
echo "   https://www.zapsplat.com/"
echo "   - High quality sound effects"
echo ""
echo "RECOMMENDED STRUCTURE:"
echo "----------------------"
echo "$SOUNDS_DIR/weather/"
echo "  ├── rain_light.ogg"
echo "  ├── rain_heavy.ogg"
echo "  ├── thunder.ogg"
echo "  ├── wind.ogg"
echo "  └── storm.ogg"
echo ""
echo "$SOUNDS_DIR/nature/"
echo "  ├── birds_morning.ogg"
echo "  ├── ocean_waves.ogg"
echo "  ├── fire_crackling.ogg"
echo "  └── forest_ambiance.ogg"
echo ""
echo "$SOUNDS_DIR/actions/"
echo "  ├── door_knock.ogg"
echo "  ├── door_close.ogg"
echo "  ├── footsteps.ogg"
echo "  ├── explosion.ogg"
echo "  └── scream.ogg"
echo ""
echo "$SOUNDS_DIR/ambient/"
echo "  ├── fireplace_loop.ogg"
echo "  ├── rain_background.ogg"
echo "  └── wind_background.ogg"
echo ""
echo "CONVERSION TOOLS:"
echo "-----------------"
echo "# Install ffmpeg if needed"
echo "sudo pacman -S ffmpeg"
echo ""
echo "# Convert WAV to OGG"
echo "ffmpeg -i sound.wav -c:a libvorbis -q:a 4 sound.ogg"
echo ""
echo "# Batch convert all WAV in directory"
echo "for f in *.wav; do ffmpeg -i \"\$f\" -c:a libvorbis -q:a 4 \"\${f%.wav}.ogg\"; done"
echo ""
echo "QUICK START PACK (Minimal):"
echo "---------------------------"
echo "Download these 10 essential sounds first:"
echo "  1. rain.ogg (weather)"
echo "  2. thunder.ogg (weather)"
echo "  3. wind.ogg (weather)"
echo "  4. birds.ogg (nature)"
echo "  5. ocean.ogg (nature)"
echo "  6. fire.ogg (nature)"
echo "  7. door.ogg (actions)"
echo "  8. footsteps.ogg (actions)"
echo "  9. fireplace_loop.ogg (ambient)"
echo " 10. rain_background.ogg (ambient)"
echo ""
echo "TEST SOUND PLAYBACK:"
echo "--------------------"
echo "# Test if sound works"
echo "paplay ~/.jarvis/sounds/weather/rain.ogg"
echo ""
echo "# Test volume adjustment"
echo "paplay --volume=32768 ~/.jarvis/sounds/ambient/rain_background.ogg  # 50% volume"
echo ""
echo "✅ Directory structure ready"
echo "⏳ Download sounds manually from sources above"
echo "📖 See docs/ENHANCED_AUDIOBOOK.md for more info"
